Repository 4T2F/PADO, pull requests merged in 2024-01, with the labels that each got.

#9 Feature/user: 회원가입 / 로그인 기능 구현 완료
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO.xcodeproj/xcshareddata/xcschemes/PADO.xcscheme
  PADO/PADO/Assets.xcassets/cursorColor.colorset/Contents.json
  PADO/PADO/Authentication/AuthenticationViewModel.swift
  PADO/PADO/Authentication/EnterAgeView.swift
  PADO/PADO/Authentication/EnterCodeView.swift
  PADO/PADO/Authentication/EnterNameView.swift
  PADO/PADO/Authentication/EnterPhoneNumberView.swift
  PADO/PADO/Authentication/MainAuthenticationView.swift
  PADO/PADO/Authentication/User.swift
  PADO/PADO/Extensions/Extensions.swift
  PADO/PADO/Helpers/PhoneumberTFFormat.swift
  PADO/PADO/Items/VerificationView.swift
  PADO/PADO/LeftMenu/Friends.swift
  PADO/PADO/MainView.swift
  PADO/PADO/PADOApp.swift
Labels: 🐞 치우, 📌 동호

#33 Feature/setting
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/GoogleService-Info.plist
  PADO/PADO/iOS/Setting/View/Components/ModalBackground.swift
  PADO/PADO/iOS/Setting/View/Components/RoundedEdge.swift
  PADO/PADO/iOS/Setting/View/Components/SettingDevider.swift
  PADO/PADO/iOS/Setting/View/DummyView.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/Setting-Extension/ViewExtension.swift
  PADO/PADO/iOS/Setting/View/SettingAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingNormalCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingRedCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingToggleCell.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 🚬 민채

#48 🐞 Fix: StartView 애니메이션 수정 및 로직 변경, 파일 정리
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PADO/PADO/Assets.xcassets/PP/person.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/person.imageset/person.png
  PADO/PADO/Assets.xcassets/PP/person.imageset/person2.png
  PADO/PADO/Assets.xcassets/PP/person.imageset/person3.png
  PADO/PADO/PADOApp.swift
  PADO/PADO/countries.json
  PADO/PADO/iOS/Helpers/Items/EnjoyButton.swift
  PADO/PADO/iOS/Helpers/Items/SignUpButton.swift
  PADO/PADO/iOS/Login/CodeView.swift
  PADO/PADO/iOS/Login/IdView.swift
  PADO/PADO/iOS/Login/StartView.swift
  PADO/PADO/iOS/Login/TextAnimation.swift
Labels: 🐞 치우

#49 🌊 Feat: 파이어스토리지를 통해 프로필 변경 및 연동
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PADO/PADO/Assets.xcassets/PP/person.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/person.imageset/person.png
  PADO/PADO/Assets.xcassets/PP/person.imageset/person2.png
  PADO/PADO/Assets.xcassets/PP/person.imageset/person3.png
  PADO/PADO/PADOApp.swift
  PADO/PADO/countries.json
  PADO/PADO/iOS/Helpers/Items/EnjoyButton.swift
  PADO/PADO/iOS/Helpers/Items/SignUpButton.swift
  PADO/PADO/iOS/Helpers/Services/ImageUploader.swift
  PADO/PADO/iOS/Login/AuthenticationViewModel.swift
  PADO/PADO/iOS/Login/CodeView.swift
  PADO/PADO/iOS/Login/IdView.swift
  PADO/PADO/iOS/Login/StartView.swift
  PADO/PADO/iOS/Login/TextAnimation.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/Component/CircularImageView.swift
  PADO/PADO/iOS/MyFeed/Component/MyFeedHeaderView.swift
  PADO/PADO/iOS/MyFeed/View/MyFeedView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: ✅ Approved

#51 Update trafico.yml
  .github/trafico.yml
Labels: 🔍 Ready for Review

#55 💄 Design: ReDesign UI 수정
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/MainView/Feed/FeedCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/MainView/Report/ReportResultView.swift
  PADO/PADO/iOS/MainView/Report/ReportSelectCellView.swift
  PADO/PADO/iOS/MainView/Report/ReportSelectView.swift
Labels: 👍 Merge 진행

#56 ✨ Add: 프로필 이미지관련 스토리지 로직 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/ImageUploader.swift
  PADO/PADO/iOS/Login/AuthenticationViewModel.swift
Labels: 👍 Merge 진행

#58 💄 Design: 댓글창 수정 및 알림 연결
  PADO/PADO/PADOApp.swift
  PADO/PADO/iOS/MainView/Comment/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/FaceMojiView.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/MainView/Report/ReportSelectView.swift
  PADO/PADO/iOS/Notification/NotificationView.swift
Labels: 👍 Merge 진행

#61 🌊 Feat: 제스쳐 추가 및 오늘 연속 커밋 100일 째 달성ㅎㅎ
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/MainView/RedesignMainView/ViewModel/MainCommentViewModel.swift
Labels: 👍 Merge 진행

#63 Feature/fcm : FCM 토큰 서버 저장 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/PADOApp.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/IdView.swift
  PADO/PADO/iOS/Login/Component/LoginCodeView.swift
  PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/PhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/TextAnimation.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Model/User.swift
Labels: 👍 Merge 진행

#64 🌊 Feat: 토큰값 새로 받고, 이전 계정으로 로그인 시 원래 토큰값으로 받아오게 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Enums/ViewState.swift
  PADO/PADO/iOS/Helpers/Extenssions/NavigationViewStyleHelper.swift
  PADO/PADO/iOS/Helpers/Interfaces/Searchable.swift
  PADO/PADO/iOS/Helpers/Items/ActivityIndicator.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MyFeed/Component/SearchView.swift
  PADO/PADO/iOS/MyFeed/View/FollowerView.swift
  PADO/PADO/iOS/MyFeed/View/FollowingView.swift
  PADO/PADO/iOS/MyFeed/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Search/MainSearchView.swift
  PADO/PADO/iOS/Search/SearchViewModel.swift
  PADO/PADO/iOS/Surfing/View/FriendCellView.swift
  PADO/PADO/iOS/Surfing/View/SurfingMakeView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👀 리뷰 요청

#65 💄 Design: 오늘 파도, 프로필 완성
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/MainView/Feed/FeedView.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Model/MainCommentModel.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/MainView/RedesignMainView/ViewModel/ViewModel.swift
  PADO/PADO/iOS/MyFeed/Component/CircularImageView.swift
  PADO/PADO/iOS/MyFeed/Component/MyFeedContentView.swift
  PADO/PADO/iOS/MyFeed/Component/MyFeedHeaderView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/MyFeed/View/MyFeedView.swift
  PADO/PADO/iOS/Notification/NotificationView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Today/Cell/TodayCell.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/Cell/TodayHeartCommentCell.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#66 📚 Docs: 주석 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/PADOApp.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/Today/Cell/TodayCell.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/Cell/TodayHeartCommentCell.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#69 🌊 Feat: 카메라 사진찍기, 이미지 불러오기 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/Camera.imageset/Camera.svg
  PADO/PADO/Assets.xcassets/MainIcon/Camera.imageset/Contents.json
  PADO/PADO/Info.plist
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👀 리뷰 요청

#70 Feature/main feed design
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/AppIcon.appiconset/1024.png
  PADO/PADO/Assets.xcassets/ColorSet/num0.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num1.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num2.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num3.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num4.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num5.colorset/Contents.json
  PADO/PADO/PADOApp.swift
  PADO/PADO/iOS/Helpers/Items/AnimatedTitleView.swift
  PADO/PADO/iOS/Helpers/Items/LoadingCircleView.swift
  PADO/PADO/iOS/Helpers/Items/LunchSTA.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Model/MainCommentModel.swift
  PADO/PADO/iOS/MainView/RedesignMainView/Model/MainFaceMojiModel.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
Labels: 🐞 치우, 📌 동호, 🚬 민채, 👍 Merge 진행

#71 🌊 Feat: 앨범, 카메라 사진 선택시 PostView에 연동
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/Camera.imageset/Camera.svg
  PADO/PADO/Assets.xcassets/MainIcon/Camera.imageset/Contents.json
  PADO/PADO/Info.plist
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#72 🌊 Feat: 로그인 데이터 받아오는 중이면 스플래시 화면 머무르게 구현
  PADO/PADO/Assets.xcassets/ColorSet/num0.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num1.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num2.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num3.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num4.colorset/Contents.json
  PADO/PADO/Assets.xcassets/ColorSet/num5.colorset/Contents.json
  PADO/PADO/iOS/MainView.swift
Labels: 👍 Merge 진행

#75 🌊 Feat: 로그아웃 구현
  PADO/PADO/PADOApp.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/IdView.swift
  PADO/PADO/iOS/Login/Component/LoginCodeView.swift
  PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/PhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#77 develop <- main: main 브랜치에서의 변경사항 적용
  .github/trafico.yml
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Items/LaunchSTA.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/Model/MainCommentModel.swift
  PADO/PADO/iOS/MainView/Feed/Model/MainFaceMojiModel.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/ViewModel.swift
  PADO/PADO/iOS/MyFeed/Component/SocialGlobeView.swift
  PADO/PADO/iOS/MyFeed/View/MyFeedView.swift
  README.md
Labels: 👍 Merge 진행

#79 Feature/swiftLint
  PADO/.swiftlint.yml
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/Setting/View/SettingInfoView.swift
  PADO/PADO/Setting/View/SettingOthersView.swift
  PADO/PADO/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/ActivityIndicator.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Items/GrayButtonView.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/Helpers/Items/PostButtonView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Helpers/Items/SignUpButton.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/IdView.swift
  PADO/PADO/iOS/Login/Component/LoginCodeView.swift
  PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/PhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/Component/MyFeedHeaderView.swift
  PADO/PADO/iOS/MyFeed/Component/SocialNetWorkBarView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/MyFeedContentView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/Notification/VerificationPostView.swift
  PADO/PADO/iOS/Setting/View/Components/SettingDivider.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/Setting-Extension/ViewExtension.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#81 develop <- main: swiftLint 적용
  PADO/.swiftlint.yml
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/Setting/View/SettingInfoView.swift
  PADO/PADO/Setting/View/SettingOthersView.swift
  PADO/PADO/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/ActivityIndicator.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Items/GrayButtonView.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/Helpers/Items/PostButtonView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Helpers/Items/SignUpButton.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/IdView.swift
  PADO/PADO/iOS/Login/Component/LoginCodeView.swift
  PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/PhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/Notification/VerificationPostView.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/Setting-Extension/ViewExtension.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행, 🔍 추가 승인 필요

#85 🌊 Feat: 오늘 파도 스크롤링 추가 및 디자인 변경
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/PP/Pic0.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/Pic0.imageset/chiwoo.jpg
  PADO/PADO/Assets.xcassets/PP/Pic4.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/Pic4.imageset/myunghyun.jpg
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Today/Model/Reel.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#86 feature/SurfingView - SurfingView 리펙토링 및 스플래시뷰 오류 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Surfing/Component/CameraAccessView.swift
  PADO/PADO/iOS/Surfing/Component/PhotoPicker.swift
  PADO/PADO/iOS/Surfing/Coordinator/CamerCoordinator.swift
  PADO/PADO/iOS/Surfing/View/FriendCellView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingMakeView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 🔍 추가 승인 필요

#88 Feature/surfing : 프로필 수정 로직 변경
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#90 🌊 Feat: MainView 모델링 및 로직 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/ViewModel.swift
Labels: 👍 Merge 진행

#91 🩹 Refactor: 스토리지 관련 함수 전역 클래스 선언
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
Labels: 👍 Merge 진행

#92 🌊 Feat: 파이어베이스에서 사진 불러오는 기능 구현
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/Model/Post.swift
Labels: 👍 Merge 진행

#93 🌊 Feat: asyncImage -> KingFisher 변경
  PADO/PADO/iOS/Helpers/Items/LoadingCircleView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
Labels: 👍 Merge 진행

#95 main <- develop: 파이어베이스 서버 변경
  PADO/.swiftlint.yml
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/Assets.xcassets/PP/Pic0.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/Pic0.imageset/chiwoo.jpg
  PADO/PADO/Assets.xcassets/PP/Pic4.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/Pic4.imageset/myunghyun.jpg
  PADO/PADO/GoogleService-Info.plist
  PADO/PADO/iOS/Helpers/Items/LoadingCircleView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/ViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/Component/CameraAccessView.swift
  PADO/PADO/iOS/Surfing/Component/PhotoPicker.swift
  PADO/PADO/iOS/Surfing/Coordinator/CamerCoordinator.swift
  PADO/PADO/iOS/Surfing/View/FriendCellView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingMakeView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/Model/Reel.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
  PADO/PADOTests/PADOTests.swift
Labels: 👍 Merge 진행

#97 Feature/surfing view : 게시글 올리는 구현
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#99 🐞 Fix: 사진, 텍스트 변경 오류 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
Labels: 👍 Merge 진행

#101 🌊 Feat: UpdateImageUrl 함수에서 Switch 구문으로 사용가능하도록 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
Labels: 👍 Merge 진행

#102 Feature/mainView: 포스팅 되어 있는 스토리셀 이미지, 이름 받아오는 기능 구현
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/User.swift
Labels: 👍 Merge 진행

#103 🌊 Feat: 게시글 포스팅 기능 구현
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Surfing/Component/CameraAccessView.swift
  PADO/PADO/iOS/Surfing/Coordinator/CamerCoordinator.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#106 🌊 Feat: 설정 - 캐시지우기 구현
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
Labels: 👍 Merge 진행

#109 🌊 Feat: 회원탈퇴 구현
  .github/ISSUE_TEMPLATE/custom.md
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MyFeed/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
Labels: 👍 Merge 진행

#110 Feature/my feed : 파이어베이스 문서 규칙 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/MyFeed/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/MyFeed/View/FollowerView.swift
Labels: 👍 Merge 진행

#113 Feature/my feed: 로그인, 계정 삭제 오류 수정
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
Labels: 👍 Merge 진행

#114 🌊 Feat: 피드 시간, 제목, 하트 수 서버에서 받아오게 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/DateFormatter.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#115 feature/SettingView - 셀 간격 조정, Divider 색 조정, 로그아웃 모달뷰 적용
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/Setting/View/Components/SettingDivider.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingViewCell.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#117 🌊 Feat: 문의하기 사진첨부 기능 구현, 세팅뷰 폰트크기 조절
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/ColorSet/modalBlackButton.colorset/Contents.json
  PADO/PADO/iOS/MyFeed/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Setting/View/SettingAskButton.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingNormalCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingRedCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingToggleCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingViewCell.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#119 💄 Design: 댓글 입력에 따라 동적으로 크기 조절 되도록 디자인 변경
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
Labels: 🚬 민채, 👨‍💻성진, 🏄🏾 명현, 👍 Merge 진행

#120 Feature/my feed : 팔로우, 언팔로우 기능 구현 완료
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/BlueButtonView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Helpers/Services/UpdateFollowData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/MyFeed/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/MyFeed/Component/FollowingCellView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/MyFeedView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift
  PADO/PADO/iOS/MyFeed/View/FollowView.swift
  PADO/PADO/iOS/MyFeed/View/FollowerView.swift
  PADO/PADO/iOS/MyFeed/View/FollowingView.swift
  PADO/PADO/iOS/MyFeed/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Notification/Cell/FollowerCell.swift
Labels: 👍 Merge 진행

#121 🌊 Feat: 파이어 베이스에서 댓글 쓰기 기능 구현
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
  PADO/PADO/iOS/Today/Cell/TodayHeartCommentCell.swift
Labels: 👍 Merge 진행

#122 💄 Design: Profile 리디자인
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/PP/B11.imageset/B11.jpeg
  PADO/PADO/Assets.xcassets/PP/B11.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/B12.imageset/B12.jpeg
  PADO/PADO/Assets.xcassets/PP/B12.imageset/Contents.json
  PADO/PADO/Assets.xcassets/PP/B14.imageset/B14.jpeg
  PADO/PADO/Assets.xcassets/PP/B14.imageset/Contents.json
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Profile/View/OffsetModifier.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👍 Merge 진행

#123 Feature/my feed : 새 프로필뷰에 기능 연결
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/MyFeedContentView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/MyFeedView.swift
  PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👀 리뷰 요청, 👍 Merge 진행

#124 Feature/redesign : 대대적인 뷰 공사
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Search/MainSearchView.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingNormalCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingRedCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingToggleCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingViewCell.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Setting/View/SettingNotificationView.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/FriendCellView.swift
Labels: 👍 Merge 진행

#127 [Add] feature/Profile SNS 뱃지 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/SNS/Contents.json
  PADO/PADO/Assets.xcassets/SNS/instagram.imageset/Contents.json
  PADO/PADO/Assets.xcassets/SNS/instagram.imageset/instagram.svg
  PADO/PADO/Assets.xcassets/SNS/tiktok.imageset/Contents.json
  PADO/PADO/Assets.xcassets/SNS/tiktok.imageset/tiktok.svg
  PADO/PADO/Assets.xcassets/instagram-logo.imageset/instagram-logo.png
  PADO/PADO/Assets.xcassets/tictok-logo.imageset/tiktok-logo.png
  PADO/PADO/iOS/Helpers/Items/SNSButton.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Profile/View/ProfileBadgeModalView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
Labels: 👍 Merge 진행

#128 [Add] feature/Search: SearchBar 디자인, 애니메이션 수정
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
Labels: 👍 Merge 진행

#130 [Add] Feature/main view : 피드 가져오기 구현 완료
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/View/FollowView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Helpers/Items/TimestampDateFormatter.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/MainView/Report/ReportSelectView.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Today/Cell/TodayHeartCommentCell.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#133 [Add] feature/Search : 팔로워/팔로잉뷰 리디자인
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowHomeView.swift
  PADO/PADO/iOS/Follow/View/FollowView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Follow/View/OffsetTabView.swift
  PADO/PADO/iOS/Follow/View/PagerHelper.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👍 Merge 진행
