Repository 4T2F/PADO, pull requests merged in 2024-02, with the labels that each got.

#137 🌊 Feat: 하트, 댓글 연결 완료
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Heart.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Model/Story.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#139 [Add] Feature/redesign Profile 수정 및 FollowerView 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/chat.imageset/chat.svg
  PADO/PADO/Assets.xcassets/MainIcon/heart.imageset/heart.svg
  PADO/PADO/Assets.xcassets/MainIcon/heart_fill.imageset/heart_fill.svg
  PADO/PADO/iOS/Follow/Component/FollowerModalAlert.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowHomeView.swift
  PADO/PADO/iOS/Follow/View/FollowMainView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Follow/View/OffsetTabView.swift
  PADO/PADO/iOS/Follow/View/PagerHelper.swift
  PADO/PADO/iOS/Helpers/Items/BlueButtonView.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👍 Merge 진행

#140 [Add] Feature/firebase - 프로필 이미지 변경시 편집기능 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#143 [Add] Feature/firebase - 페이스 모지 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Facemoji.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/Component/CameraAccessView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#147 [Add] Feature/firebase - 서퍼 지정 뷰 생성
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SuferSelectCell.swift
  PADO/PADO/iOS/Surfing/View/SuferSelectView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#149 Feature/firebase
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/firstPhoto.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/firstPhoto.imageset/firstPhoto 1.svg
  PADO/PADO/Assets.xcassets/MainIcon/firstPhoto.imageset/firstPhoto 2.svg
  PADO/PADO/Assets.xcassets/MainIcon/firstPhoto.imageset/firstPhoto.svg
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Comment.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Model/Story.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectCell.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#151 🌊 Feat : 프로필에서 게시글들 최신순으로 불러오게 구현
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
Labels: 👍 Merge 진행

#155 [Add] Feature/Mainview 버튼누르면 헤더, 스토리 셀 사라지게 구현 feat.로티
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/pado.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/pado.imageset/pado.svg
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Lottie/button.json
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
Labels: 👍 Merge 진행

#157 [Add]Feature/firebase - 댓글 삭제 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/TimestampDateFormatter.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/deleteCommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/reportCommentView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
Labels: 👍 Merge 진행

#158 [Add]Feature/fcm - 푸시 알림 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Info.plist
  PADO/PADO/NotificationObserver.swift
  PADO/PADO/PushNotificationManager.swift
  PADO/PADO/UpdatePushNotiData.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/deleteCommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/reportCommentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Model/Noti.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
Labels: 👍 Merge 진행

#159 [Add] Feature/Mainview: 새로고침 구현
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
Labels: 👍 Merge 진행

#164 [Add] Feature/Mainview: 신고 메일 발송 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Lottie/Heart.json
  PADO/PADO/iOS/Helpers/Lottie/Heart3.json
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Report/MailView.swift
  PADO/PADO/iOS/MainView/Report/ReportResultView.swift
Labels: 👍 Merge 진행

#172 🌊 Feat : 이용약관, 개인정보처리방침 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Setting/View/InfoWebView.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
Labels: 🏄🏾 명현, 👍 Merge 진행

#175 Feature/main view: 새 피드뷰에 연결
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateHeartData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteCommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteFaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiCropView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift
  PADO/PADO/iOS/MainView/Feed/Model/MainCommentModel.swift
  PADO/PADO/iOS/MainView/Feed/Model/MainFaceMojiModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/ReFeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/ReFeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Report/MailView.swift
  PADO/PADO/iOS/Report/ReportResultView.swift
  PADO/PADO/iOS/Report/ReportSelectCellView.swift
  PADO/PADO/iOS/Report/ReportSelectView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
  PADO/PADO/iOS/SwiftUIView.swift
  PADO/PADO/iOS/Today/Cell/TodayCell.swift
  PADO/PADO/iOS/Today/Cell/TodayCommentCell.swift
  PADO/PADO/iOS/Today/Cell/TodayHeartCommentCell.swift
  PADO/PADO/iOS/Today/Model/Reel.swift
  PADO/PADO/iOS/Today/View/TodayView.swift
Labels: 👀 리뷰 요청

#176 Feature/main view: 메인 피드 포스트 가져오기 구현
  PADO/PADO/iOS/MainView/Feed/View/ReFeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
Labels: 👍 Merge 진행

#179 [Add] Feature/profile 내 프로필 그리드 사진 연동
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/HighlightCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/ReceivePostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SendPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/HighlightView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/ReceivePostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SendPostView.swift
  PADO/PADO/iOS/Profile/View/PostDetailView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#180 [Add] Feature/fcm 알림 컬렉션 저장, 알림뷰 연동
  PADO/.swiftlint.yml
  PADO/NotificationService/NotificationService.swift
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/Helpers/Extensions/UserDefaultsExtension.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Helpers/Services/UpdateHeartData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePostData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiCropView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/MainView/Feed/View/ReFeedCell.swift
  PADO/PADO/iOS/Model/Noti.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Notification/Cell/AdvancedSettingsCell.swift
  PADO/PADO/iOS/Notification/Cell/CommentNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/CreateFeedCell.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FollowNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FollowerCell.swift
  PADO/PADO/iOS/Notification/Cell/HeartNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/SurferCell.swift
  PADO/PADO/iOS/Notification/Cell/SurferNotificationCell.swift
  PADO/PADO/iOS/Notification/NotificationCellView.swift
  PADO/PADO/iOS/Notification/NotificationView.swift
  PADO/PADO/iOS/Notification/NotificationViewModel.swift
  PADO/PADO/iOS/Notification/VerificationPostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/HighlightCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/ReceivePostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SendPostCell.swift
  PADO/PADO/iOS/Setting/View/SettingNotificationView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
Labels: 👍 Merge 진행

#181 [Design] Feature/Profile 전체적인 디자인 수정 작업
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/ColorSet/mainColor.colorset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/more.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/more.imageset/more.svg
  PADO/PADO/Assets.xcassets/SNS/instagramicon.imageset/Contents.json
  PADO/PADO/Assets.xcassets/SNS/instagramicon.imageset/instagramicon.svg
  PADO/PADO/Assets.xcassets/SNS/tiktokicon.imageset/Contents.json
  PADO/PADO/Assets.xcassets/SNS/tiktokicon.imageset/tiktokicon.svg
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerModalAlert.swift
  PADO/PADO/iOS/Follow/Component/FollowerOtherUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowMainView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Helpers/Items/BlueButtonView.swift
  PADO/PADO/iOS/Helpers/Items/GrayButtonView.swift
  PADO/PADO/iOS/Helpers/Items/RectangleImageView.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Feed/View/ReFeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/ReFeedView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/HighlightCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/ReceivePostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SendPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/HighlightView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/ReceivePostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SendPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileBadgeModalView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Report/ReportResultView.swift
  PADO/PADO/iOS/Report/ReportSelectView.swift
  PADO/PADO/iOS/Search/Component/RecordSearchCellView.swift
  PADO/PADO/iOS/Search/View/MainSearchView.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingAskView.swift
  PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingViewCell.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Setting/View/SettingNotificationView.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#183 Feature/main view: 프로필 피드선택 뷰 구현 완료
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Info.plist
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerOtherUserCellView.swift
  PADO/PADO/iOS/Helpers/Items/CustomRefreshView.swift
  PADO/PADO/iOS/Helpers/Items/FeedSurfers.swift
  PADO/PADO/iOS/Helpers/Items/TimestampDateFormatter.swift
  PADO/PADO/iOS/Helpers/Lottie/Loading.json
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteCommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteFaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiCropView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Notification/Cell/CommentNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FollowNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/HeartNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/SurferNotificationCell.swift
  PADO/PADO/iOS/Notification/VerificationPostView.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/Cell/OtherHighlightCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/Cell/OtherRecevePostCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/Cell/OtherSelectPostCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/Cell/OtherSendPostCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/View/OtherHighlightView.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/View/OtherReceivePostView.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/View/OtherSelectPostView.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/View/OtherSendPostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/HighlightCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/ReceivePostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
Labels: 👀 리뷰 요청

#184 [Feat] Feature/search 텍스트필드 Uikit 코드 이식
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/CustomRefreshView 2.swift
  PADO/PADO/iOS/Helpers/Items/RepresentableTextField.swift
  PADO/PADO/iOS/Helpers/Items/SearchBar.swift
  PADO/PADO/iOS/Helpers/Lottie/Loading 2.json
  PADO/PADO/iOS/Login/Component/BirthAlertModal 2.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel 2.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainCommentCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/MainFaceMojiCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedCell 2.swift
  PADO/PADO/iOS/Notification/Cell/HeartNotificationCell 2.swift
  PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell 2.swift
  PADO/PADO/iOS/Notification/Cell/SurferNotificationCell 2.swift
  PULL_REQUEST_TEMPLATE 2.md
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#189 [Add] Feature/firebase 파도타기 기능구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Services/GetPostData.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/Model/PadoRide.swift
  PADO/PADO/iOS/PadoRide/Cell/SufferInfoCell.swift
  PADO/PADO/iOS/PadoRide/Cell/SufferPostCell.swift
  PADO/PADO/iOS/PadoRide/Model/TextBox.swift
  PADO/PADO/iOS/PadoRide/View/CanvasView.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideEditView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Surfing/View/SurfingMakeView.swift
  PADO/PADO/iOS/SwiftUIView.swift
Labels: 👍 Merge 진행

#192 [Add] Feature/firebase - 파도타기 기능구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/CropWhiteBackground.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#194 Feature/main view - 피드 -> 프로필 연결
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Follow/Component/FollowerOtherUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowMainView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Helpers/Items/BlueButtonView.swift
  PADO/PADO/iOS/Helpers/Lottie/Wave.json
  PADO/PADO/iOS/Helpers/Services/CropWhiteBackground.swift
  PADO/PADO/iOS/Helpers/Services/UpdateFollowData.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteCommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectCommentView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Notification/Cell/FollowNotificationCell.swift
  PADO/PADO/iOS/PadoRide/Cell/SufferPostCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/Cell/OtherSelectPostCell.swift
  PADO/PADO/iOS/Profile/OtherUserProfileGrid/View/OtherSelectPostView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/DeleteMessageView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitCell.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Search/Component/RecordSearchCellView.swift
  PADO/PADO/iOS/Search/Component/SearchCellView.swift
  PADO/PADO/iOS/Search/View/MainSearchView.swift
Labels: 👍 Merge 진행

#195 🌊 Feat: 댓글들 유저 데이터 중복 제거 후 받아와서 저장하게 구현
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#197 [Feat] Feature/comment 오늘 파도 1~3위 메달 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/MainIcon/bronzemedal.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/bronzemedal.imageset/bronzemedal.svg
  PADO/PADO/Assets.xcassets/MainIcon/goldmedal.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/goldmedal.imageset/goldmedal.svg
  PADO/PADO/Assets.xcassets/MainIcon/silvermedal.imageset/Contents.json
  PADO/PADO/Assets.xcassets/MainIcon/silvermedal.imageset/silvermedal.svg
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/CustomRefreshView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
Labels: 👍 Merge 진행

#198 [Add]Feature/firebase - 파도타기 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/CropWhiteBackground.swift
  PADO/PADO/iOS/Helpers/Services/ImageRatioResize.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/PadoRide/View/CanvasView.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#200 [Design] Feature/SurfingView - 포스트 뷰 사진앨범 모달로 수정
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👨‍💻성진, 🏄🏾 명현, 👍 Merge 진행

#201 [Add]Feature/comment 랭킹 1위 로티 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Lottie/pokjuk.json
  PADO/PADO/iOS/Helpers/Lottie/pokjuk1.json
  PADO/PADO/iOS/Helpers/Lottie/pokjuk2.json
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
Labels: 👍 Merge 진행

#203 Feature/surfingView - 댓글, 다른유저 프로필 신고하기 연결
  PADO/PADO/iOS/MainView/Comment/View/SelectCommentView.swift
  PADO/PADO/iOS/Report/ReportCommentView.swift
  PADO/PADO/iOS/Report/ReportSelectCellView.swift
  PADO/PADO/iOS/Report/ReportUserView.swift
Labels: 🏄🏾 명현, 👍 Merge 진행

#207 [Fix] Feature/surfingView - 서핑뷰 UI 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectCell.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👨‍💻성진, 🏄🏾 명현, 👀 리뷰 요청

#215 Feat/login: 로그인 / 로그아웃 / 회원가입 앱 내에서 진행되게 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerOtherUserCellView.swift
  PADO/PADO/iOS/Follow/Component/FollowingCellView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Helpers/Items/CustomRefreshView.swift
  PADO/PADO/iOS/Helpers/Items/FollowButtonView.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateFollowData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateHeartData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/LoginCodeView.swift
  PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/PhoneNumberView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginGuideView.swift
  PADO/PADO/iOS/Login/View/LoginView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedGuideCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedHeaderCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedGuideView.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Notification/Cell/FollowNotificationCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
Labels: 👍 Merge 진행

#216 [Add] Feature/firebase - 프로필, 파도타기 디테일 작업
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Follow/View/FollowingView.swift
  PADO/PADO/iOS/Helpers/Items/NoItemView.swift
  PADO/PADO/iOS/Helpers/Services/DeleteImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/DeletePost.swift
  PADO/PADO/iOS/Helpers/Services/ImageRatioResize.swift
  PADO/PADO/iOS/Helpers/Services/UpdateUserData.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/Cell/SurfingGuideCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedGuideView.swift
  PADO/PADO/iOS/MainView/Feed/View/SurfingGuideView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/View/TouchBackImageView.swift
  PADO/PADO/iOS/Profile/View/TouchProfileView.swift
  PADO/PADO/iOS/Search/Component/SearchGuide.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👀 리뷰 요청

#218 Feature/block: 유저 차단 기능 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Helpers/Services/UpdateFollowData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift
  PADO/PADO/iOS/MainView/Feed/Cell/SurfingGuideCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/SurfingGuideView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/BlockUser.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Report/ProfileReprotModalView.swift
  PADO/PADO/iOS/Search/Component/RecordSearchCellView.swift
  PADO/PADO/iOS/Search/Component/SearchCellView.swift
  PADO/PADO/iOS/Search/View/MainSearchView.swift
  PADO/PADO/iOS/Search/ViewModel/SearchViewModel.swift
  PADO/PADO/iOS/Setting/View/Components/SettingDivider.swift
  PADO/PADO/iOS/Setting/View/SettingBlockUserView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#219 [Add] Feature/firebase - 파도, 파도타기 삭제기능 구현
  PADO/PADO/iOS/Helpers/Services/DeletePost.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
Labels: 👍 Merge 진행

#221 [Add] Feature/surfingView - 서핑뷰, 파도타기 게시하기 버튼 프로그레스 뷰 적용
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideEditView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
Labels: 🏄🏾 명현, 👍 Merge 진행

#224 [Add] Feature/firebase - 차단시 포스트 삭제 함수 구현
  PADO/PADO/iOS/Helpers/Services/DeletePost.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectCell.swift
Labels: 👍 Merge 진행

#227 [Design] Feature/ Block - 방명록 글 삭제 모달 및 자잘한 UI 수정
  PADO/PADO/iOS/PadoRide/Cell/SufferPostCell.swift
  PADO/PADO/iOS/Profile/View/DeleteMessageView.swift
  PADO/PADO/iOS/Profile/View/MessageBubbleView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Report/ProfileReprotModalView.swift
  PADO/PADO/iOS/Setting/View/SettingBlockUserView.swift
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 🏄🏾 명현, 👍 Merge 진행

#228 Feature/fcm
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Notification/Cell/CommentNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/HeartNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/PadoRideNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell.swift
  PADO/PADO/iOS/Notification/View/NotificationView.swift
Labels: 👍 Merge 진행

#229 Feature/main view : 배포 전 각종 오류 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/PostSelectModalView.swift
  PADO/PADO/iOS/Helpers/Services/DeletePost.swift
  PADO/PADO/iOS/Helpers/Services/UpdateHeartData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectCommentView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedGuideView.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitCell.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Report/ProfileReprotModalView.swift
  PADO/PADO/iOS/Report/ReportCommentView.swift
  PADO/PADO/iOS/Report/ReportSelectCellView.swift
  PADO/PADO/iOS/Report/ReportSelectView.swift
  PADO/PADO/iOS/Report/ReportUserView.swift
  PADO/PADO/iOS/Search/ViewModel/SearchViewModel.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#230 Feature/main view: 각종 오류 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/View/FollowerView.swift
  PADO/PADO/iOS/Helpers/Items/CustomTF.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Notification/Cell/CommentNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/HeartNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/PadoRideNotificationCell.swift
  PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👍 Merge 진행

#232 [Fix] Feature/block - 서핑뷰, 파도타기 네비게이션 적용 / 이용약관, 개인정보처리방침 주소 수정
  PADO/PADO/iOS/MainView/Feed/Cell/FeedHeaderCell.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingInfoView.swift
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 🏄🏾 명현, 👍 Merge 진행

#235 Feature/profile 프로필, 배경사진 터치 이벤트 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👍 Merge 진행

#236 [Add] Feature/firebase - 각종 오류 수정
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
Labels: 👍 Merge 진행

#237 [Add]Feature - 포토모지 아이콘 로티변경
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/Helpers/Lottie/photomoji.json
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiCropView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
Labels: 👍 Merge 진행

#239 Develop: 심사 전 각종 버그 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Services/DeletePost.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectView.swift
Labels: 👍 Merge 진행

#240 Develop: 심사 전 마지막 버그 수정
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
Labels: 👍 Merge 진행

#241 Feature/fcm: 설정 워딩 변경 및 알림 설정 오류 수정
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingNotificationView.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
Labels: 👏 Merge 완료

#242 [Add] Feature/firebase - 요청 사항 추가 및 수정
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
Labels: 👍 Merge 진행

#243 Feature/profile
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
Labels: 👍 Merge 진행

#244 Develop: 배포 1.0.1버전
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingNotificationView.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
Labels: 👍 Merge 진행

#245 🐞 Fix: 각종 오류 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteFaceMojiView.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행

#246 출시버전 V.1.0.1
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/MainView/Comment/View/DeleteFaceMojiView.swift
  PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideEditView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👍 Merge 진행, 🔍 추가 승인 필요

#247 🐞 Fix: 프로필 Disappear 오류 수정
  PADO/PADO/iOS/Helpers/Extensions/Color+.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#249 Feature/profile: 버전 1.0.2 업데이트 변경사항
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Items/LaunchSTA.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Notification/Cell/PostitNotificationCell.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행, 🔍 추가 승인 필요

#250 🌊 Feat: 프로필 닉네임 없으면 아이디 보여주게 구현
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#252 [Add] Feature/firebase - 사용자 피드백 반영
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👀 리뷰 요청

#254 Develop : 배포버전 1.0.2
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Helpers/Extensions/Color+.swift
  PADO/PADO/iOS/Helpers/Items/LaunchSTA.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/Model/Post.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Notification/Cell/PostitNotificationCell.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Setting/View/SettingOthersView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요

#257 [Design] Feature/onboarding 파도타기 리디자인
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Items/NoItemView.swift
  PADO/PADO/iOS/PadoRide/Redesign/Cell/FollowerSuggestionCell.swift
  PADO/PADO/iOS/PadoRide/Redesign/Cell/SelectPadoRideUserCell.swift
  PADO/PADO/iOS/PadoRide/Redesign/View/PadoRideView1.swift
  PADO/PADO/iOS/PadoRide/Redesign/View/SelectUserView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Search/Component/SearchGuide.swift
  PADO/PADO/iOS/Search/View/MainSearchView.swift
Labels: 👀 리뷰 요청

#258 [Add] Feature/firebase - 파도 보내기 원본이미지 사용기능
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
Labels: 👀 리뷰 요청, 👍 Merge 진행

#260 Develop: 배포버전 1.0.3
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/Assets.xcassets/Onboarding/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/followerpic.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/followerpic.imageset/followerpic.svg
  PADO/PADO/Assets.xcassets/Onboarding/ridepic1.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/ridepic1.imageset/ridepic1.svg
  PADO/PADO/Assets.xcassets/Onboarding/ridepic2.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/ridepic2.imageset/ridepic2.svg
  PADO/PADO/Assets.xcassets/Onboarding/ridepic3.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/ridepic3.imageset/ridepic3.svg
  PADO/PADO/Assets.xcassets/Onboarding/ridepic4.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/ridepic4.imageset/ridepic4.svg
  PADO/PADO/Assets.xcassets/Onboarding/ridepic5.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/ridepic5.imageset/ridepic5.svg
  PADO/PADO/Assets.xcassets/Onboarding/selectpic.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/selectpic.imageset/selectpic.svg
  PADO/PADO/Assets.xcassets/Onboarding/surfpic.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/surfpic.imageset/surfpic.svg
  PADO/PADO/Assets.xcassets/Onboarding/visitpic.imageset/Contents.json
  PADO/PADO/Assets.xcassets/Onboarding/visitpic.imageset/visitpic.svg
  PADO/PADO/Assets.xcassets/TabBarImage/tab_add.imageset/tab_add.svg
  PADO/PADO/Assets.xcassets/TabBarImage/tab_added.imageset/Contents.json
  PADO/PADO/Assets.xcassets/TabBarImage/tab_added.imageset/tap_added.svg
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerModalAlert.swift
  PADO/PADO/iOS/Helpers/Items/CircularImageView.swift
  PADO/PADO/iOS/Helpers/Items/CustomTabView.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/Helpers/Items/NoItemView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedGuideView.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/SurfingGuideView.swift
  PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
  PADO/PADO/iOS/PadoRide/Cell/FollowerSuggestionCell.swift
  PADO/PADO/iOS/PadoRide/Cell/SelectPadoRideUserCell.swift
  PADO/PADO/iOS/PadoRide/Cell/SufferInfoCell.swift
  PADO/PADO/iOS/PadoRide/Cell/SufferPostCell.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideOnboardingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/View/SelectUserView.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Report/ProfileReprotModalView.swift
  PADO/PADO/iOS/Search/Component/SearchGuide.swift
  PADO/PADO/iOS/Search/View/MainSearchView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
  PADO/PADO/iOS/Surfing/View/PostCropView.swift
  PADO/PADO/iOS/Surfing/View/PostView.swift
  PADO/PADO/iOS/Surfing/View/SurfingOnboardingView.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectCell.swift
  PADO/PADO/iOS/Surfing/View/SurfingSelectView.swift
  PADO/PADO/iOS/Surfing/View/SurfingView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👀 리뷰 요청, 👍 Merge 진행, 🔍 추가 승인 필요

#262 Feature/fcm: 알림 로직 수정
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Helpers/Items/FollowButtonView.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Notification/Cell/PostitNotificationCell.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
Labels: 👍 Merge 진행

#263 Feature/detail - 버전 1.0.4 로직 추가
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/WelcomeView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/Notification/View/NotificationView.swift
  PADO/PADO/iOS/Notification/ViewModel/NotificationViewModel.swift
  PADO/PADO/iOS/PadoRide/Cell/FollowerSuggestionCell.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👍 Merge 진행

#266 [Add] Feature/firebase - 포토피커 동영상 선택 못하게
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
Labels: 👍 Merge 진행

#269 Develop : 배포버전 1.0.4
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/AppDelegate.swift
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Follow/Component/FollowerUserCellView.swift
  PADO/PADO/iOS/Helpers/Items/CustomRefreshView.swift
  PADO/PADO/iOS/Helpers/Items/CustomTabView.swift
  PADO/PADO/iOS/Helpers/Items/FollowButtonView.swift
  PADO/PADO/iOS/Helpers/Items/LoginAlert.swift
  PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift
  PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift
  PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift
  PADO/PADO/iOS/Login/Component/BirthView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/Login/Component/UseIDModalView.swift
  PADO/PADO/iOS/Login/View/LoginGuideView.swift
  PADO/PADO/iOS/Login/View/SignUpView.swift
  PADO/PADO/iOS/Login/View/StartView.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentView.swift
  PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/FeedView.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Model/GlobalVariable.swift
  PADO/PADO/iOS/Model/User.swift
  PADO/PADO/iOS/Notification/Cell/PostitNotificationCell.swift
  PADO/PADO/iOS/Notification/View/NotificationView.swift
  PADO/PADO/iOS/Notification/ViewModel/NotificationViewModel.swift
  PADO/PADO/iOS/PadoRide/Cell/FollowerSuggestionCell.swift
  PADO/PADO/iOS/PadoRide/View/DrawingView.swift
  PADO/PADO/iOS/PadoRide/View/PadoRideView.swift
  PADO/PADO/iOS/PadoRide/View/SendPadoView.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/PostitView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
  PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
  PADO/PADO/iOS/Setting/View/ModalAlertView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
  PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift
Labels: 👍 Merge 진행

#271 [Add] Feature/firebase - 프로필, 포토모지 오류 수정
  PADO/PADO/iOS/Helpers/Items/CustomTabView.swift
  PADO/PADO/iOS/Helpers/Services/DeleteImageUrl.swift
  PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift
  PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
  PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift
  PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift
  PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingProfileModal.swift
  PADO/PADO/iOS/Setting/View/SettingProfileView.swift
  PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
Labels: 👍 Merge 진행

#276 Develop: 배포버전 1.0.7
  PADO/PADO.xcodeproj/project.pbxproj
  PADO/PADO/iOS/ContentView.swift
  PADO/PADO/iOS/Login/Component/CodeView.swift
  PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift
  PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift
  PADO/PADO/iOS/Model/GlobalVariable.swift
  PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift
  PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift
  PADO/PADO/iOS/Profile/View/ProfileView.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingNormalCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingRedCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingToggleCell.swift
  PADO/PADO/iOS/Setting/View/SettingCell/SettingViewCell.swift
  PADO/PADO/iOS/Setting/View/SettingView.swift
Labels: 👀 리뷰 요청, 🔍 추가 승인 필요
